### ISSUE TITLE
Improvement Next.JS With Docker - Multiple Deployment Environments

### ISSUE THREAD

**Issue by NiKrause** [NiKrause/plebbit-indexer#1]
Improve the Next.JS container with  https://github.com/vercel/next.js/tree/canary/examples/with-docker-multi-env

e.g.

- Environment Variable Handling: Our current setup already uses environment variables (NEXT_PUBLIC_API_BASE_URL, NODE_ENV), but the example shows a more robust way to handle them using .env files for different environments (development, production, etc.).
- Build Optimization: The example demonstrates how to optimize the Docker build process for Next.js applications, which could help reduce your image size and improve build times.
- Multi-stage Builds: The example uses multi-stage builds to separate the build environment from the production environment, which is a best practice for Docker images.
- To implement these improvements, you could modify your plebindex service in the docker-compose.yml to use a multi-stage build. Here's how you could enhance it

```
services:
  plebindex:
    build:
      context: ./plebindex
      target: ${NODE_ENV:-development}  # Allows switching between development and production
      args:
        NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}
    ports:
      - "3000:3000"
    volumes:
      - ./plebindex:/app
      - /app/node_modules  # Prevents local node_modules from overwriting container's
    environment:
      - NODE_ENV=${NODE_ENV}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"
```

We would then need to create a Dockerfile in the plebindex directory that implements the multi-stage build pattern. This would help optimize the build process and make it more maintainable.

The example also shows how to handle different environments (development, production) more effectively, which could be useful if we need to deploy your application in different environments.
